spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://124.70.67.204:26000/demo?ApplicationName=app?serverTimezone=CST
    username: mcfly
    password: ks123456@@
  thymeleaf:
  　　cache: false #重点是这个要设置false不然会无效
  　　suffix: .html
  　　mode: HTML5
  　　encoding: UTF-8
  mail:
    host: smtp.qq.com
    username: 1486147017@qq.com
    password: rzrzcvatmxnojhbg
    port: 587
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml

custom:
  labels: [擅长前端,擅长后端,擅长报告,擅长数据库,擅长答辩]
  schools: [南京理工大学,南京大学]
admin:
  user: root
  pwd: 123